# Generated by Django 5.2 on 2025-04-08 03:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_add_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('math_percentile', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reading_percentile', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('writing_percentile', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overall_percentile', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.RemoveIndex(
            model_name='assessment',
            name='assessment_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancerecord',
            name='attendance_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='course_code_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enrollment_period_idx',
        ),
        migrations.RemoveIndex(
            model_name='performancemetrics',
            name='performance_period_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='student_id_idx',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade_level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='lunch_type',
            field=models.CharField(default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='math_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='student',
            name='parental_education',
            field=models.CharField(default='high school', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='race_ethnicity',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='reading_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='student',
            name='test_preparation',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='writing_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='studentperformancemetrics',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.student'),
        ),
    ]
